"""initial schema

Revision ID: 0c9d84350053
Revises: 
Create Date: 2026-08-11 23:08:31.554120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c9d84350053'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_ts', 'budget_events', ['created_at'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('limit_micros', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('warn_threshold', sa.Float(), nullable=False),
    sa.Column('hard_threshold', sa.Float(), nullable=False),
    sa.Column('substitution_threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("period IN ('monthly','daily','per_session')", name='ck_budget_period'),
    sa.CheckConstraint("scope IN ('team','agent','session')", name='ck_budget_scope'),
    sa.CheckConstraint('limit_micros > 0', name='ck_budget_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'scope_id', 'period', name='uq_budget_scope_period')
    )
    op.create_table('call_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('requested_model', sa.String(length=80), nullable=False),
    sa.Column('served_model', sa.String(length=80), nullable=True),
    sa.Column('substituted', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_micros', sa.BigInteger(), nullable=False),
    sa.Column('actual_micros', sa.BigInteger(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_ledger_agent_ts', 'call_ledger', ['agent_id', 'created_at'], unique=False)
    op.create_index('ix_ledger_period', 'call_ledger', ['period'], unique=False)
    op.create_index('ix_ledger_team_ts', 'call_ledger', ['team_id', 'created_at'], unique=False)
    op.create_table('model_catalog',
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('input_micros_per_1k', sa.BigInteger(), nullable=False),
    sa.Column('output_micros_per_1k', sa.BigInteger(), nullable=False),
    sa.Column('tier_rank', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index(op.f('ix_model_catalog_provider'), 'model_catalog', ['provider'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preferred_model', sa.String(length=80), nullable=False),
    sa.Column('allow_substitution', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','paused','blocked','deleted')", name='ck_agent_status'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_agents_team_id'), 'agents', ['team_id'], unique=False)
    op.create_index('uq_agent_team_name_live', 'agents', ['team_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('policies',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('fallback_chain', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('limit_micros', sa.BigInteger(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_agent_id'), 'sessions', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_agent_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('policies')
    op.drop_index('uq_agent_team_name_live', table_name='agents', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_agents_team_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('teams')
    op.drop_index(op.f('ix_model_catalog_provider'), table_name='model_catalog')
    op.drop_table('model_catalog')
    op.drop_index('ix_ledger_team_ts', table_name='call_ledger')
    op.drop_index('ix_ledger_period', table_name='call_ledger')
    op.drop_index('ix_ledger_agent_ts', table_name='call_ledger')
    op.drop_table('call_ledger')
    op.drop_table('budgets')
    op.drop_index('ix_events_ts', table_name='budget_events')
    op.drop_table('budget_events')
    # ### end Alembic commands ###
