"""per-agent runaway threshold

Revision ID: 1ed85e8ec1b0
Revises: 0c9d84350053
Create Date: 2026-08-11 23:30:20.433791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed85e8ec1b0'
down_revision: Union[str, Sequence[str], None] = '0c9d84350053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('runaway_hourly_fraction', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'runaway_hourly_fraction')
    # ### end Alembic commands ###
