"""model catalog: provider routing fields

Revision ID: 2292b336bde7
Revises: 1ed85e8ec1b0
Create Date: 2026-08-12 12:05:13.994994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2292b336bde7'
down_revision: Union[str, Sequence[str], None] = '1ed85e8ec1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    The NOT NULL columns carry server defaults so existing catalog rows are
    backfilled in the same statement — without them PostgreSQL rejects the ALTER
    outright on a populated table. Existing models are OpenAI-schema and were
    seeded rather than added by hand, which is exactly what these defaults say.
    """
    op.add_column(
        'model_catalog',
        sa.Column('provider_kind', sa.String(length=24), nullable=False,
                  server_default='openai'),
    )
    op.add_column('model_catalog', sa.Column('base_url', sa.String(length=300), nullable=True))
    op.add_column('model_catalog', sa.Column('api_key_env', sa.String(length=80), nullable=True))
    op.add_column(
        'model_catalog',
        sa.Column('is_custom', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('model_catalog', sa.Column('context_window', sa.Integer(), nullable=True))
    op.add_column('model_catalog', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column(
        'model_catalog',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_catalog', 'created_at')
    op.drop_column('model_catalog', 'notes')
    op.drop_column('model_catalog', 'context_window')
    op.drop_column('model_catalog', 'is_custom')
    op.drop_column('model_catalog', 'api_key_env')
    op.drop_column('model_catalog', 'base_url')
    op.drop_column('model_catalog', 'provider_kind')
    # ### end Alembic commands ###
