"""live controls: freeze, boost, rate limits

Revision ID: 6c923a7d14ad
Revises: a5beb074828d
Create Date: 2026-08-12 14:22:11.403594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c923a7d14ad'
down_revision: Union[str, Sequence[str], None] = 'a5beb074828d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_grants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('micros', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grants_agent_period', 'budget_grants', ['agent_id', 'period'], unique=False)
    op.add_column('agents', sa.Column('rpm_limit', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('tpm_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'tpm_limit')
    op.drop_column('agents', 'rpm_limit')
    op.drop_index('ix_grants_agent_period', table_name='budget_grants')
    op.drop_table('budget_grants')
    # ### end Alembic commands ###
