"""fallback chains: cross-provider opt-in and custom chains

Revision ID: a5beb074828d
Revises: 2292b336bde7
Create Date: 2026-08-12 12:21:15.466579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5beb074828d'
down_revision: Union[str, Sequence[str], None] = '2292b336bde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('allow_cross_provider', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('policies', sa.Column('is_custom', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'is_custom')
    op.drop_column('agents', 'allow_cross_provider')
    # ### end Alembic commands ###
