"""team freeze columns

Revision ID: aae8e6273609
Revises: 6c923a7d14ad
Create Date: 2026-08-12 14:22:43.123500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae8e6273609'
down_revision: Union[str, Sequence[str], None] = '6c923a7d14ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('teams', sa.Column('frozen_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'frozen_reason')
    op.drop_column('teams', 'frozen_at')
    # ### end Alembic commands ###
